version: '3.8'

services:
  backend:
    build: .
    ports:
      - "6969:6969"
    restart: unless-stopped
    container_name: rsgo-backend
    networks:
      - rsgo-network

networks:
  rsgo-network:
    driver: bridge